### ISSUE TITLE
bad line enders in windows compilation

### ISSUE THREAD

**Issue by brentrandol** [bytePro17124/DM-Power-Core-Version#36]
Hey There, 
I'm new to github so forgive me if this is not the place for this comment.  I saw your post on Reddit the other day and decided to try compiling your program.  I get a ton of warnings during compilation that the line enders are bad, and sure enough, the ends of every line have some bogus characters.  Any idea how to fix this, besides going through every line manually and removing the end of line character?  Otherwise, very interesting and useful tool to have, so just wanted to let you know that I enjoyed messing around with it.  I've been trying to build something similar myself in Python.  If I have the time, I may mess around with the code and submit some pull requests.  I have quite a few features I'd like to see implemented, like being able to more completely edit the characters you build.
Cheers,
Brent

**Comment by bytePro17124** [comment]
This works fine for commenting on something that is an issue. Thank you for checking out the code. Hmm I'm not sure what to think about the line ender thing, that's new to me. What program are you opening the files with? Maybe it is putting a different endline character in the file for some reason.

**Comment by brentrandol** [comment]
Sorry I should have said.  I am using visual c++ (specifically Visual Studio 2015) in Windows 7 to compile the code, which it does successfully, after I installed boost.  I've attached some sample output from the program.  I've encountered issues like this before when someone wrote their code on a Mac.  In that case it was relatively easy to go in and remove the line enders by hand because the code was so short.  Just wondering if you had any plans to go cross-platform.  I guess I could download and install cygwin and run it from there.  Or maybe I compiled it wrong?  I could try recompiling and at least taking some screenshots so you can see what I did.

![bad line enders example](https://cloud.githubusercontent.com/assets/15862804/12686713/52cfb978-c699-11e5-820f-df2473d40bfa.png)

**Comment by bytePro17124** [comment]
Ohhh. Yeah those are the color codes that are linked to the color.h file. I have seen them like that before, usually on certain terminals that emulate and don't have the capability of changing colors.

**Comment by brentrandol** [comment]
OK thanks.  So I just removed the content of the escape codes from colors.h and it works without those annoying things but also with no color.  I did some research and apparently getting windows cmd.exe to recognize ANSI characters is impossible.  There are work-arounds but they are all fairly involved.  And none of them were OS independent.

**Comment by bytePro17124** [comment]
I see. In Windows I use Cygwin. I haven't really played around with visual
studio much yet.

**Comment by brentrandol** [comment]
OK.  I got it working (with color) in cygwin, after installing boost.  Thanks!

**Comment by bytePro17124** [comment]
Cool.
